import {Toaster} from '@/components/ui/sonner'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center h-dvh">
        <main className="w-[700px] bg-white p-6 rounded-xl text-black">
        {children}
        </main>
        <Toaster/>
        </body>
    </html>
  )
}
